### PR TITLE
dollar issues

### PR DESCRIPTION
**Pull request by smaddy**
United States Dollar => United States dollar https://en.wikipedia.org/wiki/United_States_dollar
Bahamian Dollar => Bahamian dollar https://en.wikipedia.org/wiki/Bahamian_dollar

### CODE REVIEW

**Comment by mledoze** [comment]
Hello @smaddy, thank you for this fix, but there are merge conflicts between your branch and master. Could please fix these merge conflicts?

**Comment by smaddy** [comment]
do it urself, fkn lazy dude

**Comment by mledoze** [comment]
@smaddy I am not lazy, I can't push to **your branch** `smaddy/countries:master` that's why I asked.

**Comment by mledoze** [comment]
The fix is merged on master https://github.com/mledoze/countries/commit/26fd4f65bf91355be7aa8b3ef507d3b413dcdc2b

**Pull request closed without merging**
