### PR TITLE
Finnish translations

### PR DESCRIPTION
**Pull request by Newman101**
Added Finnish translations for countries which names start with letter A. Continuing to B as soon as I can. :-)

Have a great weekend.

### CODE REVIEW

**Comment by mledoze** [comment]
@Newman101 thank you for this first batch! Do you mind finishing all translations before I merge this pull request?

**Comment by Newman101** [comment]
Sure thing, I'll do all translations before merging. :)

**Comment by mledoze** [comment]
Thank you for your help!

**Comment by Newman101** [comment]
C done, started with D.

**Comment by herrniemand** [comment]
@Newman101 are you doing it manually?

**Comment by Newman101** [comment]
Yes, using Aptana to edit the JSON.

**Comment by herrniemand** [comment]
@Newman101 you wanna translation script that uses google translation for it?

**Comment by Newman101** [comment]
Well, this is the problem - I need to double check the translations by Google especially with official names. It seems to be that Google does a lot of errors with Finnish language in general, and official country names are no different. I can certainly try that script out but there are errors, I can promise you that. :D

**Comment by herrniemand** [comment]
@Newman101 give me a minute

**Comment by herrniemand** [comment]
@Newman101 https://gist.github.com/herrniemand/85ece91cba119775f9e1

**Comment by Newman101** [comment]
As I suspected, it's full of errors by translation engine.

**Comment by herrniemand** [comment]
@Newman101 would that be easier to fix mistakes then do fully manual translations?

**Comment by Newman101** [comment]
True that, it's a bit easier.

**Comment by herrniemand** [comment]
@Newman101 if you want I can merge changes you have already did?

**Comment by herrniemand** [comment]
@Newman101 I have merged your changes.
https://gist.github.com/herrniemand/85ece91cba119775f9e1

**Comment by herrniemand** [comment]
@Newman101 P.S. You need to do pull from mledoze. You are 10 commits behind.

**Comment by Newman101** [comment]
Oh, ok. I will do that then.

**Comment by Newman101** [comment]
Thanks for notifying.

**Comment by herrniemand** [comment]
@Newman101 good luck *)

**Comment by mledoze** [comment]
@herrniemand thank you for your help on this :+1:

**Comment by Newman101** [comment]
Happy to help as always. :) I've pulled the repo now, it's up to date on my side.

**Comment by herrniemand** [comment]
@mledoze *)

**Comment by Newman101** [comment]
There was some merge conflicts but I've completed the localization now. =)

**Comment by mledoze** [comment]
Good work! Don't worry about the merging conflicts, I'll handle them and merge this pull request tomorrow. Again, thank you!

**Comment by Newman101** [comment]
You're welcome, happy to assist as always. =)

**Comment by mledoze** [comment]
@Newman101 it's merged! :+1: I'll make a new release soon.

**Pull request merged**
