### PR TITLE
Fix official names of Finland

### PR DESCRIPTION
**Pull request by Ohcanep**

### CODE REVIEW

**Comment by herrniemand** [comment]
@Ohcanep I am currently working on new ```native names object``` discussed #86 . Until then It will be hard to merge, so I will include your changes into my commit, and reference you in the description.

**Comment by herrniemand** [comment]
@Ohcanep and its actully [```Suomi```](https://fi.wikipedia.org/wiki/Suomi)  not ```Suomen```.
Just thought you would want to know.*)

**Comment by mledoze** [comment]
@herrniemand you included the fixes in #107? If yes, we could close this PR.

**Comment by mledoze** [comment]
@Ohcanep thank you for the fix!

**Comment by herrniemand** [comment]
@mledoze it is included. You can close PR.

**Comment by herrniemand** [comment]
@Ohcanep thanks for the fix*)

**Pull request closed without merging**
