### PR TITLE
Added README for dist/ folder to stop people from commiting into it.

### PR DESCRIPTION
**Pull request by herrniemand**
I think it looks spectacular... XD

### CODE REVIEW

**Comment by mledoze** [comment]
Thank you for that, it makes sense, though I cannot merge right now, I'll be off for a few days.

**Comment by herrniemand** [comment]
@mledoze Algood. Happy new year!*)

**Comment by mledoze** [comment]
Happy new year to you too! :-)

**Comment by mledoze** [comment]
@herrniemand could you please change to text with the following: 

```markdown
## Attention
### This distribution folder contains generated data.
### Do not commit any changes here. 
### For more information, please read [CONTRIBUTING.md](https://github.com/mledoze/countries/blob/6d65afb38a48545ec0a6c35043b541c1fa285657/CONTRIBUTING.md).
### Thank you.
```

I removed capital letters, it's better without them.
Thank you.

**Comment by herrniemand** [comment]
@mledoze There you go*)

**Comment by mledoze** [comment]
@herrniemand thank you!

**Comment by herrniemand** [comment]
@mledoze Pas de problème...

**Pull request merged**
