### PR TITLE
Add ISO 3166-2 names

### PR DESCRIPTION
**Pull request by ruimarinho**
Add mapping for ISO 3166 names.

### CODE REVIEW

**Comment by jjlharrison** [comment]
Shouldn't the names be unicode escaped ("\u00c5land Islands" instead of "Åland Islands")? There is an inconsistency with the common names.

**Comment by ruimarinho** [comment]
Ah, yes, indeed. Thanks for pointing that out. Regarding the common inconsistency, I don't have any suggestion right now. Any idea?

**Comment by ruimarinho** [comment]
@jjlharrison, escaping fixed.

**Comment by jjlharrison** [comment]
Great. The inconsistency I was referring to was the unescaped characters. All looks good to me now. Thanks.

**Comment by mledoze** [comment]
@ruimarinho thank you for this, but I don't understand the difference with the `name.common` property, it appears to be the same for each country.

**Comment by ruimarinho** [comment]
@mledoze I've moved the new key closer to `common` so that you can see the differences. Here's a diff:

| Common | ISO 3166 |
|--------|----------|
| French Southern and Antarctic Lands | French Southern Territories |
| Bonaire | Bonaire, Sint Eustatius and Saba |
| Bolivia | Bolivia, Plurinational State of |
| Brunei | Brunei Darussalam |
| Ivory Coast | Côte d'Ivoire |
| DR Congo | Congo, the Democratic Republic of the |
| Republic of the Congo | Congo |
| Falkland Islands | Falkland Islands (Malvinas) |
| Micronesia | Micronesia, Federated States of |
| Heard Island and McDonald Islands | Heard Island and McDonald Mcdonald Islands |
| Iran | Iran, Islamic Republic of |
| South Korea | Korea, Republic of |
| Laos | Lao People's Democratic Republic |
| Macau | Macao |
| Saint Martin | Saint Martin (French part) |
| Moldova | Moldova, Republic of |
| Macedonia | Macedonia, the Former Yugoslav Republic of |
| Pitcairn Islands | Pitcairn |
| North Korea | Korea, Democratic People's Republic of |
| Palestine | Palestine, State of |
| Russia | Russian Federation |
| South Georgia | South Georgia and the South Sandwich Islands |
| São Tomé and Príncipe | Sao Tome and Principe |
| Sint Maarten | Sint Maarten (Dutch part) |
| Syria | Syrian Arab Republic |
| Taiwan | Taiwan, Province of China |
| Tanzania | Tanzania, United Republic of |
| Vatican City | Holy See (Vatican City State) |
| Venezuela | Venezuela, Bolivarian Republic of |
| British Virgin Islands | Virgin Islands, British |
| United States Virgin Islands | Virgin Islands, U.S. |
| Vietnam | Viet Nam |

**Comment by ruimarinho** [comment]
Not sure if there's a need to distinguish between ISO 3166-1, 3166-2 and 3166-3..

**Comment by mledoze** [comment]
> Not sure if there's a need to distinguish between ISO 3166-1, 3166-2 and 3166-3.

Indeed, that's what I was thinking. For the countries where spellings differ, there is the `altSpellings` property. A good candidate is `Macau` and `Macao`.

**Comment by herrniemand** [comment]
@mledoze Agree. That would be the best solution.
@ruimarinho IMHO current implementation is literally ugly. Just the implementation, not the idea. No offence.

**Comment by ruimarinho** [comment]
Actually, shouldn't `official` be the name from ISO 3166?

**Comment by mledoze** [comment]
> Actually, shouldn't `official` be the name from ISO 3166?

In a diplomatic context, I would say yes but in this case I don't think that it's a good idea because of the way the names are written: `Korea, Republic of` is less intuitive than `Republic of Korea`.

**Comment by ruimarinho** [comment]
Ok, fair enough. I don't think this is an `altSpelling` though, because it is part of an ISO standard, making it closer to `official` than `alternative`. Is the key name `iso3166` being discussed here or the content?

**Comment by ruimarinho** [comment]
@mledoze anything I can do to get this merged?

**Comment by ruimarinho** [comment]
@mledoze sorry for being a PITA, but any chance of looking at this?

**Comment by mledoze** [comment]
@ruimarinho I'm sorry for the late reply, I'm a bit busy right now, I'll come back to you as soon as possible.

**Comment by mledoze** [comment]
@ruimarinho the only problem I have with the ISO 3166-2 names is that it contains a lot of information already available in the `names` property. Also the format, *e.g.* `Tanzania, United Republic of` is in my opinion not better than the official name *i.e.* `United Republic of Tanzania`, in a project like this one.

To not throw everything away I would prefer to only keep the different spellings in country names like `Macau` and `Macao` or `Vietnam` and `Viet Nam`, and put these in the `altSpellings` property.

**Comment by ruimarinho** [comment]
I see your point. The problem, however, is that some projects require the ISO 3166-2 name property to be exactly like the ISO standard, so `Tanzania, United Republic of` won't match `Tanzania`. I think that's a good alternative though - would you accept all differences to be included in the `altSpellings` property - i.e., `Tanzania, United Republic of` listed as the `altSpelling` of `Tanzania`?

**Comment by mledoze** [comment]
@ruimarinho 
> would you accept all differences to be included in the `altSpellings` property

yes very good idea, it's even better than what I proposed in my last comment.

**Comment by ruimarinho** [comment]
Check my most recent commit, it's done already :)

**Comment by mledoze** [comment]
Yeah I saw that, I'm merging it now.

**Comment by mledoze** [comment]
@ruimarinho it's done, thank you for this :+1: I hope it'll be useful for you!

**Comment by ruimarinho** [comment]
For reference, the data was sourced from http://data.okfn.org/data/core/country-list or, more precisely, http://data.okfn.org/data/core/country-list/r/data.json. 

Thank you for your patience on this one :) are you up for a patch release?

**Comment by mledoze** [comment]
> are you up for a patch release?

yes but not tonight :wink:

**Comment by ruimarinho** [comment]
@mledoze any chance of releasing it soon :)? Thanks!

**Comment by mledoze** [comment]
@ruimarinho yes this week. It's good for you?

**Comment by ruimarinho** [comment]
Yeah, sure, thanks a lot!

**Comment by ruimarinho** [comment]
Thank you :)

**Pull request merged**
