### PR TITLE
Allow Symfony 2.6 and 2.7

### PR DESCRIPTION
**Pull request by DraperStudio**

### CODE REVIEW

**Comment by mledoze** [comment]
Hi, I just tested the build script with Symfony 2.7 and it works fine. Could please change to `~2.7` only please?

**Comment by mledoze** [comment]
Thank you! Merging now.

**Comment by mledoze** [comment]
I'll post a new release now.

**Comment by mledoze** [comment]
Done: https://github.com/mledoze/countries/releases/tag/v1.7.4

**Comment by DraperStudio** [comment]
Thanks!

**Pull request merged**
