### PR TITLE
Add 'currencies' with code, name and symbol

### PR DESCRIPTION
**Pull request by fayder**

### CODE REVIEW

**Comment by fayder** [comment]
@porsager I have a similar PR here. It adds `code`, `name` and `symbol`. Unfortunately the formatting of the JSON is a bit different because I use an automated script. I added the `currencies` fields and kept the current `currency` one, but I can remove the latter if needed.

**Comment by porsager** [comment]
The naming generally does seem a bit off. I think it would be great if names were corrected such that singular and plural was used correctly depending on the data, but I didn't want to change too much in my PR, just add the data.. Perhaps a 3rd PR including your changes and the extras (decimals and INT code i mentioned in my PR) :P

**Comment by mledoze** [comment]
@fayder @porsager thank you for your work! I like both of them but we'll need to do some additional work to merge them. 

I think we should rename the `currency` property to `currencies` to be consistent with other properties like `borders`, `languages` and `translations`. Also could you please reorder keys inside the `currencies` property so that there are listed in alphabetic order?

> I think it would be great if names were corrected such that singular and plural was used correctly depending on the data

@porsager could you elaborate on what needs to be changed please?

> Perhaps a 3rd PR including your changes and the extras (decimals and INT code i mentioned in my PR) :P

I will accept this current pull request, but I'd love another pull request with decimals and numeric code.

Thank you :)

**Comment by mledoze** [comment]
@fayder also make sure to update your branch with the latest changes on master, I merge a few pull requests yesterday.

**Comment by fayder** [comment]
@mledoze Thanks for you reply! So I'll do the following very soon:
- Solve merge conflict
- Remove current `currency` (to be replaced with new `currencies`)
- Order key names inside `currency`

**Comment by fayder** [comment]
I think it's good now

**Comment by mledoze** [comment]
Thank you @fayder I'll look into it.

**Comment by mledoze** [comment]
@fayder I reviewed your latest changes. The `currencies` property is very good, except that there are some incorrect values:
```
            {
                "code": "(none)",
                "name": null,
                "symbol": null
            }
```
or 
```
            {
                "code": "(none)",
                "name": "[E]",
                "symbol": "$"
            }
```
For currencies which don't have a code, I prefer to put `null` instead of `(none)`.

Also, I would prefer that we keep the current keys ordering for each countries, I mean the one that is defined in the [README.md](https://github.com/mledoze/countries/blob/f45a4ca1eacfcfad5536526c98b1dd26cc7a2e44/README.md).

Could you please fix these issues?

**Comment by fayder** [comment]
@mledoze Thanks for the feedback. I'll take a look soon

**Comment by fayder** [comment]
@mledoze I have made improvements to the PR. Btw, the source of the currencies is this https://en.wikipedia.org/wiki/List_of_circulating_currencies

**Comment by mledoze** [comment]
Hello @fayder, sorry for the delay. 

Thank you for your improvements. However I would like to make a final change to it. I would like to keep the idea from @porsager's pull request (#301) and change the format `currencies` like so:

```
  "currencies": {
    "NAD": {
      "name": "Namibian dollar",
      "symbol": "$"
    },
    "ZAR": {
      "name": "South African rand",
      "symbol": "R"
    }
  }
```
That way I will be easier to get the name of a currency by its code instead of by its index in the array.

Could you please make this change?

Thank you

**Comment by fayder** [comment]
@mledoze Happy holidays. I've updated this PR once again

**Comment by fayder** [comment]
New conflict. Will resolve it tomorrow!

**Comment by mledoze** [comment]
@fayder I still see some conflicts between this branch and master
```
$ git pull https://github.com/fayder/countries.git currencies
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 28 (delta 11), reused 14 (delta 10), pack-reused 13
Unpacking objects: 100% (28/28), done.
From https://github.com/fayder/countries
 * branch            currencies -> FETCH_HEAD
Auto-merging countries.json
CONFLICT (content): Merge conflict in countries.json
Automatic merge failed; fix conflicts and then commit the result.
```
Could you please update this branch from master of https://github.com/mledoze/countries?

**Comment by fayder** [comment]
@mledoze conflict solved

**Comment by mledoze** [comment]
Thank you @fayder, I will merge this today.

**Comment by mledoze** [comment]
@porsager @fayder it's merged on master, thank you for all the great work!

**Comment by mledoze** [comment]
Also thank you for your patience :)

**Pull request merged**
