### PR TITLE
added Arabic translations to all countries

### PR DESCRIPTION
**Pull request by MrSltun**
**Few things worth mentioning:**
- Followed the three-letter ISO 639-3 language code in adding Arabic.
- Escaped all Arabic characters.

### CODE REVIEW

**Comment by mledoze** [comment]
@MrSltun @sombek

We now have two similar pull requests to add arabic translations, that's fantastic but I don't know which one to accept :/

Also, I see that some translations differ, for example the official name of New Caledonia:
in this pull request we have `\u0643\u0627\u0644\u064A\u062F\u0648\u0646\u064A\u0627 \u0627\u0644\u062C\u062F\u064A\u062F\u0629`

and in #262 we have `\u0643\u0627\u0644\u064A\u062F\u0648\u0646\u064A\u0627\u0020\u0627\u0644\u062C\u062F\u064A\u062F\u0629`

Which one is correct?

**Comment by sombek** [comment]
@mledoze 
The difference in the above example is just a space character `\u0020`.
I think both of them are okay.
If there are some differences we can check it out and choose the proper one.

**Comment by mledoze** [comment]
> The difference in the above example is just a space character \u0020.

Yes I also saw that difference. Could you please check the two pull requests and propose the one that should be merged?

**Comment by MrSltun** [comment]
Ok cool, I will be working with @sombek to merge our changes, but I will change something I just noticed yesterday, Saudi Arabia's common name in
```JSON
"name": {
    "native": {
        "ara": {
            "common": "\u0627\u0644\u0633\u0639\u0648\u062f\u064a\u0629"
	}
    }
},
```
is not the same common one we use in the Arab world, we just call it Saudi.

**Comment by sombek** [comment]
Hey @MrSltun 
How are things going?

**Comment by mledoze** [comment]
@sombek @MrSltun 

I will now release the version 2.0.0 of this project and will include these translations in another release, for example v2.1.0.

**Comment by mledoze** [comment]
I will close this pull request for now. Feel free to reopen it when you are ready.

**Comment by MrSltun** [comment]
Hi @mledoze, I updated the branch added the Arabic translation to it again.

**Comment by MrSltun** [comment]
Hi @mledoze,

I just updated my branch and added the Arabic translation again to countries.json, and regenerated the `dist` files, but I don't seem to have the rights to reopen this pull request, can you please reopen it for me?

Thanks

**Comment by mledoze** [comment]
@MrSltun the PR is open again.

**Comment by claesjacobsson** [comment]
What's the status of this?

**Comment by MrSltun** [comment]
@claesjacobsson It is updated with master now

**Comment by MrSltun** [comment]
@mledoze please review it and merge it if everything is good

**Comment by claesjacobsson** [comment]
@mledoze Any chance of merging and releasing this soon. Thanks!

**Comment by guibranco** [comment]
@mledoze any updates on this ?

**Comment by yasseralsaidi** [comment]
any update?

**Comment by MrSltun** [comment]
Closing this since it's out of date now

**Pull request closed without merging**
