### PR TITLE
Changed Kosovo cca3 code from KOS to UNK. #159

### PR DESCRIPTION
**Pull request by herrniemand**
As discussed in #159

### CODE REVIEW

**Comment by herrniemand** [comment]
@mledoze there ya go mate! *)

**Comment by herrniemand** [comment]
@mledoze shit. What tha. Give me a sec I will fix something.

**Comment by mledoze** [comment]
No problem, take your time.

**Comment by herrniemand** [comment]
@mledoze Done. *)

**Comment by herrniemand** [comment]
@mledoze No worries*)

**Pull request merged**
