### PR TITLE
Add Korean translations

### PR DESCRIPTION
**Pull request by is343**
Added Korean translations. Also added a few alternate spellings for North and South Korea.

I tried my best to keep the formatting as close as I could!

### CODE REVIEW

**Comment by is343** [comment]
Gah! Looks like there was another PR that was merged an hour ago.

**Comment by mledoze** [comment]
Hello @is343, thank you for this pull request.



> Gah! Looks like there was another PR that was merged an hour ago.

Yes, I merged the Urdu translations earlier today. Would you be able to resolve the merge conflicts?

**Comment by mledoze** [comment]
Besides that, you pull request looks good :+1:

**Comment by is343** [comment]
Yeah, I'll try to get this resolved shortly

**Comment by is343** [comment]
Should be good to go!

**Comment by is343** [comment]
@ mledoze any update on this?

**Comment by mledoze** [comment]
Hello @is343 it's merged now. Thank you for your help and your patience 👍

**Pull request merged**
