### PR TITLE
Correct the file permissions

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log

- Correct the file permissions to be the `10644` excluding `countries.php` and `ci/test.sh` becasue the they seem to be the executable file.

### CODE REVIEW

**Comment by mledoze** [comment]
Thank you for this. Can you please add an entry to the changelog?

**Comment by peter279k** [comment]
> Thank you for this. Can you please add an entry to the changelog?

The entry has been added. If having any request change, please let me know :).

**Comment by peter279k** [comment]
PIN @mledoze

**Comment by mledoze** [comment]
I'm sorry for the delay, I'm on vacation right now, I'll merge it this week. Thank you for your patience.

**Pull request merged**
