### PR TITLE
travis ci config

### PR DESCRIPTION
**Pull request by paulvollmer**
#201

### CODE REVIEW

**Comment by mledoze** [comment]
@paulvollmer I just pushed your branch as https://github.com/mledoze/countries/tree/test-travis-ci to test your file. You can see the first build here: https://travis-ci.org/mledoze/countries/jobs/195188671

**Comment by mledoze** [comment]
I think it would be better to use the PHP language so that we can add PhpUnit tests in the future.

https://github.com/mledoze/countries/blob/test-travis-ci/.travis.yml

@paulvollmer what do you think?

**Comment by paulvollmer** [comment]
i think it is not needed to test the different languages (at the moment) because only the json files are linted and the linter runs 4 times with the same data...

if the php tests are implemented, we can switch back to the test matrix you've configured.

_for now we can reduce the test time at travis if we only test one php version_

**Comment by mledoze** [comment]
> if the php tests are implemented, we can switch back to the test matrix you've configured.
> 
> for now we can reduce the test time at travis if we only test one php version

Ok for me 👍

**Comment by paulvollmer** [comment]
#204 is the new PR

**Comment by paulvollmer** [comment]
if it's merged into the master we can add the nice travis badge to the readme

**Comment by mledoze** [comment]
> #204 is the new PR

so we can close this one?

**Pull request closed without merging**
