### PR TITLE
#419 Added missing tags.

### PR DESCRIPTION
**Pull request by khamsolt**

### CODE REVIEW

**Comment by mledoze** [comment]
Hello @khamsolt
thank you for this, I will review it shortly.

**Comment by khamsolt** [comment]
@mledoze Hi, I wanted to remind you, we really need these fixes.

**Comment by khamsolt** [comment]
We still believe and wait with hope, like Hachiko ...

**Comment by khamsolt** [comment]
@mledoze we need your help.

**Comment by mledoze** [comment]
Hi, I'm sorry for the delay, I was on vacation and couldn't handle your PR.

It's merged now.

**Comment by khamsolt** [comment]
@mledoze Thank you, and thank you for the cool package =)

**Comment by mledoze** [comment]
You're welcome, I'm glad it is useful to you.

**Pull request merged**
