### PR TITLE
Slovak translation

### PR DESCRIPTION
**Pull request by Nabela**
all states translated to slovak language
correction of subregion in Slovak Republic from eastern to central
correction of capital letter in spanish version of Islas Salomon (from islas Salomon to Islas Salomon)

### CODE REVIEW

**Comment by mledoze** [comment]
Hello @Nabela, thank you for this. I'll review your PR soon.

**Comment by Zetberg** [comment]
+1

**Comment by Nabela** [comment]
+1

**Comment by mledoze** [comment]
Hello @Nabela 

here it is, it's merged. Sorry for the delay, I've been pretty busy in July and August.

It seems that there is some translations missing for Honduras, Macau and Samora. Could you please add these?

Thank you.

**Comment by Nabela** [comment]
We don't have translation for these countries. Should i put the same name anyway?

**Comment by mledoze** [comment]
@Nabela yes you can do that.

**Pull request merged**
