### PR TITLE
TimeZone information added, as well as PHP parser/updater.

### PR DESCRIPTION
**Pull request by semsono**
The data is downloaded from latest public tzdata database.
Update script: parse data and save changes to countries.json
Shows result running via cli: Parsed 416 tz records; +added:416 -removed:0

### CODE REVIEW

**Comment by herrniemand** [comment]
@semsono Partially related to your commit:
Have you seen [Gilmore Davidson : Timezone of your life | JSConf.au 2014](https://www.youtube.com/watch?v=FvTcR2NTobo) ?

**Comment by mledoze** [comment]
@herrniemand thank you, very interesting!

**Comment by semsono** [comment]
Thanks, great time problem presentation indeed. Partially confirms my reasons to provide TZ select for user application, but particularly liked the example with Jira. It based not only on TZ string but also provides the offset number for proper zone picking, so I think to add offset also. Something like "tz":[["Europe/Lisbon", "+00"]]

What do you think about it? Should I use other library data to provide TZ picker?
But I'd love to have TZ info on this project.

**Comment by herrniemand** [comment]
@semsono I agree with you. It would be cool idea. But I have concern about timezones, specifically keeping it up to date, summer time, etc. How will you perform that?

**Comment by semsono** [comment]
Well, good question!

In case of the app that is the Calendar with timed alerts, we got a Customer with Europe/Moscow tz UTC+04, who created the sms/email alert at (2014 March 9) for (2014 November 3, 11:00), local time. Nice! 

So, in case of my mega big app I will store 3 Alert time data parameters: 
Local Time (2014-11-03 11:00:00)
UTC Time (2014-11-03 07:00:00)
TimeZone (Europe/Moscow)

Cool, now the mega cronjob runs every UTC minute and select * from alerts WHERE utc_time < NOW()  /massive

There is only one problem - in case if we dont care about updating TZ data. If so, on planed day our customer will receive the alert at 10:00 and not at 11:00 as he wanted. Yes, the public TZ was updated on June 2014 with changes: since October 26, 2014 - Europe/Moscow has UTC +3 and not +4 as was on alert creation date.

No problem, as we know TZ changes lets update records: update alerts set utc_time = utc_time-1 where timezone='Europe/Moscow' and localtime > '2014-10-26 00:00:00'

Still very good question, how can I get updated? 
Maybe in case of regular Countries.json release with TZ names and offset updated - I can scan the file and compare if the TZ offset is the same on my alert records by difference between Local and UTC time!

Back to countries.json - I was thinking that having updated data for TZ picker would be great for this kind of library anyway. You just need to run "php tzupdate.php && php countries.php" before release, better with updated php version.

**Comment by semsono** [comment]
Also since having TZ string there is no need of storing offset info - we can get it easily from updated system!

**Comment by herrniemand** [comment]
@semsono ```updated system``` you mean user?

**Comment by semsono** [comment]
@herrniemand yes, I mean client side we have browsers updated with latest tz-db, so I can get data from TZ. As well as php or other server sides that gets the data from os system based on TZ.

**Comment by mledoze** [comment]
@semsono how often are the timezones updated?

**Comment by semsono** [comment]
The data get updated 5 and more times per year, but this not always TZ removes or additions, most of changes is about offset changes for the past. In 2014, at least 2 TZ was removed, 2 added, and some locations changed the TZ. Its a hell.

**Comment by mledoze** [comment]
@semsono oh, I thought this data was static :confused:. In this case I'm less inclined to add timezone data. Last year, population data was removed (see https://github.com/mledoze/countries/issues/6#issuecomment-42322804) especially because it need to be updated regularly for all countries.

However if we don't include the time offsets and only a few entries need to be updated each year, I'm ok with that.

**Comment by semsono** [comment]
@mledoze I think updating the TimeZone list once a year is ok since we store only the tz string. That will not be exactly recent data - but its a great start to provide the TZ picker for customer.

**Comment by herrniemand** [comment]
@semsono @mledoze here is the list of changes in timezones http://www.timeanddate.com/news/time/.
I have mixed feelings about this pull request.
On the one side its cool to have timezones. On another hand its a frequently changed data that need to be constantly updated.

**Comment by semsono** [comment]
@herrniemand yeah, I understand your fear but I still convinced )

The most of changes along of year affect the tz-database, so keep my customers cool I'll do this: 
- they pick their TZ from countries; 
- I will notify them to update the browser if will work with sensitive data TZ, on client-side (via Moment for ex, that access DateTime object from browser).
- on server side (unix) - I need to get my system updated, in order to get my stored timezones working as expected.

The TZ info is a kind of just static data for apps, in most of cases. Don't see critical problem in case of little outdated tz options.

**Comment by mledoze** [comment]
@semsono I'm sorry about this one but TZ data change too frequently. However I don't think your work will be lost. I'm thinking about a feature where regurlarly changing data such as population data or timezones could be included at build time. For example: 

```shell
php convert.php convert --extra=tz,population
```
What do you think?

**Comment by semsono** [comment]
@mledoze right now for the problem I used moment/moment-timezone tz-list available, for customer its free input with auto suggest tz list. With Countries library I can get tz per country, and this is also very useful. But yes, looks like moment-tz team is doing good job on releases.

Anyway including tz optionally here would be awesome, thank you!

**Pull request closed without merging**
