### PR TITLE
Fix CCA2 and alternative spellings for Norway

### PR DESCRIPTION
**Pull request by sensen**
NO is reserved keyword in YAML. It'll become `false` when loaded instead
of literal NO.

http://yaml.org/type/bool.html

### CODE REVIEW

**Comment by petert82** [comment]
This is going to be a bit of a pain to fix properly. The Symfony YAML component that is being used to dump the country data to YAML 'mostly' implements [YAML 1.2][1] where boolean values can only be represented as `true` or `false`. It doesn't quote strings that would be interpreted as boolean values (`'yes'`, `'no'`, `'on'`, `'off'`, etc) by parsers implementing older versions of the YAML spec.

I'm going to raise an issue with the Symfony Yaml component to ask if they would consider a patch to quote these values when dumping to YAML.

[1]: http://www.yaml.org/spec/1.2/spec.html#id2803629

**Comment by sensen** [comment]
@herrniemand I wasn't aware of this. As @petert82 said, the proper way to fix this issue is by fixing the Symfony YAML component.

**Comment by mledoze** [comment]
@sensen thank you for raising this issue, I'll close it for now and wait for a fix on the Symfony YAML component.

**Comment by petert82** [comment]
Just for reference, this should be fixed once [this PR][1] is accepted. I'll make sure to keep an eye on it and update the composer.json here, if necessary once this is done.

[1]: https://github.com/symfony/symfony/pull/13262

**Comment by mledoze** [comment]
@petert82 very good, thank you! I'll keep an eye on it too.

**Comment by shehi** [comment]
@mledoze I strongly recommend against closing such issues - why don't you wait with it open and not miss the issue when Symphony fixes things at their side?

**Comment by mledoze** [comment]
The pull request https://github.com/symfony/symfony/pull/13262 has been merged into v2.6.4. I updated the dependencies in https://github.com/mledoze/countries/commit/a3c480d57c6fa1bd8fcb60c1528620b8b2dc1bd0.

**Pull request closed without merging**
