### PR TITLE
Merge demonym into demonyms

### LINKED ISSUE #368: Merge `demonym` into `demonyms`
As a followup to #343, we need to merge the `demonym` property into `demonyms` to avoid duplication.

Ping @alexsegura

### PR DESCRIPTION
**Pull request by alexsegura**
Fixes #368

### CODE REVIEW

**Comment by mledoze** [comment]
Thank you for this. Do you mind putting `eng` before `fra` to respect the alphabetic order?

**Comment by alexsegura** [comment]
@mledoze here you go

At first I thought it wouldn't be possible as object properties would get serialized in an unpredictable order, but it's as simple as setting the object keys in the order you expect. 

💙PHP 💙

```php
<?php

$countries = json_decode(file_get_contents('./countries.json'));

foreach ($countries as $key => $country) {
    if (isset($country->demonyms) && isset($country->demonym)) {

        $demonyms_eng = new \stdClass();
        $demonyms_eng->f = $country->demonym;
        $demonyms_eng->m = $country->demonym;

        $demonyms = $country->demonyms;

        unset($country->demonym);
        unset($country->demonyms);

        $country->demonyms = new \stdClass();

        $countries[$key]->demonyms->eng = $demonyms_eng;
        $countries[$key]->demonyms->fra = $demonyms->fra;
    }
}

file_put_contents('./countries.json', json_encode($countries, JSON_PRETTY_PRINT));

```

**Comment by mledoze** [comment]
Or you could just use `ksort`; here is a tested example:

```php
$countries = json_decode(file_get_contents('countries.json'), true);

$countries = array_map(static function ($country) {
    if (isset($country['demonyms'], $country['demonym'])) {
        $country['demonyms']['eng'] = [
            'f' => $country['demonym'],
            'm' => $country['demonym'],
        ];
        ksort($country['demonyms']);
        unset($country['demonym']);
    }
    return $country;
}, $countries);

file_put_contents('countries.json', json_encode($countries, JSON_PRETTY_PRINT));
```

**Comment by mledoze** [comment]
Could you also remove the description of the `demonym` property in the `README`?

**Comment by alexsegura** [comment]
Done.

**Comment by mledoze** [comment]
It's merged, thank you for your help on this. I will draft a new release now.

**Pull request merged**
