### PR TITLE
Added independent flag according to ISO 3166-1

### LINKED ISSUE #252: Suggestion: include 'independent' flag
Not every country listed is an independent nation, e.g. 'Åland Islands' ([ISO 3166-2:AX](https://en.wikipedia.org/wiki/ISO_3166-2:AX)).

[ISO 3166-1 alpha-2](https://www.iso.org/obp/ui/#iso:pub:PUB500001:en) contains a flag 'independent':
```
<?xml version="1.0" encoding="UTF-8" standalone="true"?>
   <country version="52" id="BR">
      ...
      <independent>YES</independent>
      ...
```

Suggested change:
Updating countries.json with an independent flag for each country.

Example:
`"independent": true`

Data source: e.g. [Wikipedia ISO-3166-1](https://en.wikipedia.org/wiki/ISO_3166-1)

Optional: add relationship of the dependency, e.g. 'Åland Islands' -> 'Finland'

### PR DESCRIPTION
**Pull request by blumk**
Added independent flag according to ISO 3166-1, fixes #252.

_Skipped record for XK (Kosovo) as it is not listed as official country in ISO 3166-1 (therefore it can't be dependent/independent). I recommend removing this record in order to be compliant with ISO 3166-1, see #253._

**Data validation**
[Wikipedia ISO-3166-1](https://en.wikipedia.org/wiki/ISO_3166-1)
Total countries: 249
Independent: 194
Dependent: 55

countries.json:
Total countries: 248
Independent: 194
Dependent: 53 _=> BQ (Bonaire,...) #254, SH (St. Helena, ...) #255_  
null: 1 _=> XK (Kosovo) #253_

Removing XK and adding BQ + SH (248 -1 +2) equals the expected 249 countries.

### CODE REVIEW

**Comment by mledoze** [comment]
@blumk thank you for this pull request, I'll review it soon.

**Comment by blumk** [comment]
@mledoze Instead of removing the record XK (Kosovo) you could extend the record with:
`"independent": null,`
I've proposed a solution how to handle this record by adding a status flag in #253.

**Comment by blumk** [comment]
@mledoze I've set the Kosovo record to `"independent": null,`, I think this is an elegant way to keep the record in the dataset.

As soon as you merge this change I'll start working on the status flag mentioned in #253. My goal is to make this dataset compliant with ISO-3166-1.

**Comment by mledoze** [comment]
@blumk thank you for your work.

> I've set the Kosovo record to "independent": null,, I think this is an elegant way to keep the record in the dataset.

I find the solution to be elegant too.

Could you please add this flag to documentation in the README?

**Pull request merged**
