### PR TITLE
Replaced Kosovo's International Olympic Committee code by ISO 3166-1 …

### PR DESCRIPTION
**Pull request by honza-kasik**
…alpha-3 code in land borders array

There is a mixup in using ISO 3166-1 alpha-3 and International Olympic Committee codes. All other countries are described in form of ISO 3166-1 alpha-3 code but Kosovo is described by International Olympic Committee code - `KOS`.

### CODE REVIEW

**Comment by mledoze** [comment]
@honza-kasik thank you for this patch.

**Comment by herrniemand** [comment]
@mledoze didn't we had this issue before?

**Comment by herrniemand** [comment]
@mledoze #159 #160

**Comment by mledoze** [comment]
@herrniemand yes, it's seems there were still some bugs about that.

**Comment by herrniemand** [comment]
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3, 
"UNK identifies Kosovo residents to whom travel documents were issued by the United Nations Interim Administration in Kosovo (UNMIK)". I will contact UNMIK first, and confirm such information, first.

**Comment by herrniemand** [comment]
@mledoze Sorry. I've seen this issue two days ago. Too busy with uni and stuff.

**Comment by herrniemand** [comment]
@honza-kasik @mledoze Sorry. I am a bit tired. @honza-kasik Thank you for fix.

**Comment by herrniemand** [comment]
@honza-kasik dekuju*)

**Comment by mledoze** [comment]
@herrniemand don't worry, no hurry ;)

**Comment by herrniemand** [comment]
@mledoze *)

**Comment by honza-kasik** [comment]
@mledoze @herrniemand No problem! I am happy to help! ;)

**Pull request merged**
