### PR TITLE
Spanish translations and native names for Bonaire and Curaçao

### PR DESCRIPTION
**Pull request by cumanacr**
Added spanish translations for both and native names for Bonaire only
Regards,

### CODE REVIEW

**Comment by herrniemand** [comment]
@cumanacr XD

**Comment by cumanacr** [comment]
@herrniemand 
I learning a lot with this project not only about countries 
:cherries: :cherries: :cherries: LOL

**Comment by herrniemand** [comment]
@cumanacr XD. I've just looked on my first commits #69 . I know how you feel XD

**Comment by cumanacr** [comment]
@herrniemand, wow! that was messy indeed, I feel better, gracias gracias gracias, I love git too :smile:

**Comment by herrniemand** [comment]
@cumanacr XD

**Comment by herrniemand** [comment]
@cumanacr try this http://nieman.de/posts/2014/11/24/git-basics/ . Yes it is my post. From my website. But try. *)

**Comment by cumanacr** [comment]
@herrniemand, thanks!!! :smile: 
I have a little question, if ok, how often do you merge pull request?

**Comment by herrniemand** [comment]
@mledoze is the maintainer. I am just helping here buy answering
questions and adding new staff.

2015-02-28 13:47 GMT+13:00, Cristian Umaña <notifications@github.com>:

**Comment by cumanacr** [comment]
@herrniemand understood, thanks.

**Comment by mledoze** [comment]
@cumanacr sorry for the late merge, thank you for your contribution :+1:!

**Pull request merged**
