### PR TITLE
Major update: Implemented new native name object. Updated translations.

### PR DESCRIPTION
**Pull request by herrniemand**
## Updates:
 - Added ```German``` language to ```Italy```. See [South Tyrol](https://en.wikipedia.org/wiki/South_Tyrol).

 - South Africa's native names. LOVE AFRIKAANS WIKIPEDIA!!! :heart_eyes:

 - Fixed ```Norwegian languages```:
	 - Removed ```nor:Norwegian``` entry for Norwegian.
	 - Renamed ```Nynorsk``` and ```Bokmål``` to ```Norwegian Nynorsk``` and ```Norwegian Bokmål``` accordingly.
	 - Added ```Sami``` language to the language lists.
	 - Links:
	 	 - https://en.wikipedia.org/wiki/Nynorsk
	 	 - https://en.wikipedia.org/wiki/Bokm%C3%A5l
	 	 - https://en.wikipedia.org/wiki/Sami_languages
	 	 - https://en.wikipedia.org/wiki/Norway

 - Fixed ```Finland``` name as proposed by @Ohcanep at #105 pull request. Big thanks to him, I nearly missed Finland problem.

 - Added ```Belizean Creole``` to Belize.

 - Fixed ```Bangladesh``` names.

 - Added all native names as discussed in #86 

 - Updated ```ALPHA-3``` codes for regional language variation.
	- Sources used:
		 - German
		 - [German](https://en.wikipedia.org/wiki/German_language)
		 - [Swiss German](https://en.wikipedia.org/wiki/Swiss_German)
		 - [Austrian German](https://en.wikipedia.org/wiki/Bavarian_language)

## Issues:

 - Zimbabwe changes:
 	 - ```Zimbabwe```'s name in ```Zimbabwe Sign Language``` set to English variant as it hard to represent hands movement in UTF-8. Any suggestions about solving this problem would be appreciated.
 	 - ```Northern Ndebele```, ```Xhosa```, ```Khoisan```, ```Kalanga```, ```Tswana```, ```Chibarwe```, ```Tsonga```, ```Venda```, ```Tonga```, ```Sotho```, ```Ndau```, ```Shona```, ```Chewa``` set to English due to lack of translations on the Internet.

 - Sahrawi Arab Democratic Republic ```Berber``` name been set to English due to lack of data on this languages on Internet.

 - ```Carolinian``` name for ```Northern Mariana Islands``` been set to English due to lack of data on this languages on Internet

 - ```Kwangali```, ```Ndonga```, ```Khoekhoe```, ```Lozi```, ```Herero``` translation for Namibia been set to English due to lack of data on this languages on Internet. Any help would be useful

 - ```New Zealand```'s name in ```New Zealand Sign Language``` set to English variant as it hard to represent hands movement in UTF-8. Any suggestions about solving this problem would be appreciated.

### CODE REVIEW

**Comment by herrniemand** [comment]
@mledoze despite the fact that we had to add every single native name, and new translations, the size mostly stayed the same. There were only 77 countries that had more then one language. So most of them I've done with python script. The translation were placed in line rather then expand it for.

**Comment by herrniemand** [comment]
@mledoze althou it did earned another 150kb of weight...

**Comment by mledoze** [comment]
@herrniemand thank you for this massive update, very good work! Please give me some time to review this PR and I'll merge it today or tomorrow.

**Comment by herrniemand** [comment]
@mledoze I guess you will have as much fun reviewing it, as I writing it XD

**Comment by mledoze** [comment]
@herrniemand #103 has been merged, you're next ;)

**Comment by herrniemand** [comment]
@mledoze oooh! EXCITEMENT!!! XD

**Comment by mledoze** [comment]
@herrniemand merged into master. Again, thank you!

**Comment by herrniemand** [comment]
@mledoze happy too. Love this project*)

**Pull request merged**
