### PR TITLE
Fixing US and Canadian IDD suffixes.

### PR DESCRIPTION
**Pull request by martinheidegger**
I noticed that the Canada had an suspiciously empty IDD suffix list. With a quick check there indeed seems to exist IDD codes for Canada. 😉 

Following the Wikipedia list on [North American IDD number codes][1], this PR adds all canadian province codes that were previously missing. Also, I noticed that some of the US IDD codes were missing. Most interestingly 710 - us government, but also all [PCS][2] numbers besides some other numbers where the reason for its prior absence is unclear.

_Sorry: Composer is still not working on my computer_

[1]: https://en.wikipedia.org/wiki/List_of_North_American_Numbering_Plan_area_codes#Area_codes_by_state,_province_or_country
[2]: https://en.wikipedia.org/wiki/Personal_communications_service_(NANP)

### CODE REVIEW

**Comment by mledoze** [comment]
Hi, thank you for this update. Could you please resolve the merge conflicts on `CHANGELOG.md`?

**Comment by martinheidegger** [comment]
@mledoze  done

**Comment by mledoze** [comment]
Thank you @martinheidegger

**Comment by martinheidegger** [comment]
Thank you as well! Awesome work. When do you see a 4.2 release happening?

**Comment by martinheidegger** [comment]
> When do you see a 4.2 release happening?

ping @mledoze

**Comment by mledoze** [comment]
> When do you see a 4.2 release happening?

I will release it today. Sorry for the delay.

**Comment by mledoze** [comment]
@martinheidegger it's done https://github.com/mledoze/countries/releases/tag/v4.1.0 :)

**Comment by martinheidegger** [comment]
Awesome 👍 thank you!

**Pull request merged**
