### PR TITLE
Adding Arabic & Persian Translation

### PR DESCRIPTION
**Pull request by sombek**
Hello there!
We translated the countries in Arabic and Persian with the help of @Abeerm171.
All the strings are encoded in UTF-8.

Thanks

### CODE REVIEW

**Comment by blumk** [comment]
Thank you @sombek.

There are some minor issues:
- Following translations are missing for cca2-code: CN, MO, SG, TW
- package.json changed without any real changes

I cannot confirm the actual translations, @mledoze: can you help out with that?

**Comment by mledoze** [comment]
@blumk thank you for your review.

I don't have any knowledge in arabic or persian.
@sombek what is the source of these translations?

**Comment by sombek** [comment]
@blumk The 4 mentioned above are fixed. Also HK was missing, now it is fixed.

@mledoze I am a native Arabic speaker. I translated them with the help of google translation for some countries, also looked at wikipedia to check the official names for some countries.
Neither me have any knowledge in Persian @Abeerm171 will tell us her sources.

**Comment by Abeerm171** [comment]
My native is Arabic but I’m learning Persian and i translates  some countries based in me background knowledge  , also i back to Wikipedia for official translation and some Iranian friends

**Comment by blumk** [comment]
@mledoze I'd merge it in, looks like at least two people have taken a look at it. And then wait for feedback from the community, worst case would be reverting the change later on.

As soon as you merge some of the open pull request I'll start working on the other open issues and fix some of the older pull requests like "Support for multiple capitals" and the emoji PR.

**Comment by mledoze** [comment]
@sombek, @Abeerm171 thank you for the good work!

@blumk you're right, I'll merge this.

> Let me know if you need help maintaining this project.
Of course, any help is welcome :)

**Comment by blumk** [comment]
@sombek @Abeerm171 Looks like you've changed the file permissions, can you revert the change to package.json?
https://stackoverflow.com/questions/1257592/how-do-i-remove-files-saying-old-mode-100755-new-mode-100644-from-unstaged-cha

**Comment by mledoze** [comment]
@sombek friendly ping :)

Could you please revert the changes to the `package.json` file? I would like to include your translations in the upcoming 1.9.0 release.

Thank you.

**Comment by sombek** [comment]
@mledoze Sorry for the delay. Fixed.
Let me know if there are any issues with it.

**Comment by mledoze** [comment]
@sombek do you think it would be possible to only include persian translations? I ask this because there is another pull request for arabic translations. I would love to accept both pull requests but I fear to have huge merge conflicts between the two.

**Comment by sombek** [comment]
@mledoze Hello what happened to the pull request?

**Comment by sombek** [comment]
anything new?

**Comment by mledoze** [comment]
I will close this pull request for now. Feel free to reopen it when you are ready.

**Comment by yasseralsaidi** [comment]
any update?

**Pull request closed without merging**
