### PR TITLE
Add geojson and topojson for South Sudan (SSD)

### LINKED ISSUE #349: South Sudan is empty, but Sudan has it included
There are problems with both South Sudan country map and Sudan country map. The South Sudan map is empty: https://github.com/mledoze/countries/blob/master/data/ssd.geo.json

The Sudan country map is not empty, but it includes South Sudan, which is obviously wrong as well: https://github.com/mledoze/countries/blob/master/data/sdn.geo.json

What can be done about this? Are there known editors that I can use to edit Sudan GEO JSON file to make South Sudan out of it?

### PR DESCRIPTION
**Pull request by jamespwilliams**
Currently, this repo doesn't contain geojson or topojson for South Sudan (ISOA3 SSD), and the files for Sudan include South Sudan's region.

This MR brings the files for South Sudan and Sudan in line with the current Natural Earth dataset - i.e: South Sudan has its own region, and Sudan's region now doesn't include South Sudan.

The files from this MR have been converted from Natural Earth's data (in particular, https://www.naturalearthdata.com/downloads/10m-cultural-vectors/) using QGIS.

Fixes #349

### CODE REVIEW

**Comment by jamespwilliams** [comment]
Just noticed the other geojson files in this repo use a different format to the ones introduced in this MR (`FeatureCollection` vs `GeometryCollection`). Will fix now

**Comment by mledoze** [comment]
Hello @jamespwilliams thank you for your contribution.

Could you please add an entry in the changelog?

**Comment by jamespwilliams** [comment]
Hi, sure, I've just added an entry to the changelog

**Comment by mledoze** [comment]
It's merged, thank you.

**Pull request merged**
