### PR TITLE
International Olympic Committee codes (ioc)

### PR DESCRIPTION
**Pull request by cumanacr**
I'm glad to start adding the International Olympic Committee codes (ioc)

* README.MD
 * description for new ioc field added
 * examples updated

* ioc codes so far
 * Costa Rica
 * All letter A countries

Data taken from:
http://en.wikipedia.org/wiki/List_of_IOC_country_codes

### CODE REVIEW

**Comment by cumanacr** [comment]
I added ioc codes all the way until "L", dist files not updated yet, I'll continue after lunch :fork_and_knife:

**Comment by cumanacr** [comment]
Work done!
I hope you like it and merge it

**Comment by mledoze** [comment]
@cumanacr thank you for the good work! Could you please move the `ioc` property below `cca3` so that country codes are together? If not, no problem.

**Comment by cumanacr** [comment]
Sure!, I'm working on it

**Comment by cumanacr** [comment]
btw, I'm changing `ioc` to `cioc` to maintain the 4 letter length on codes's properties, to keep the "standard" and for easy reading the codes too

**Comment by cumanacr** [comment]
@mledoze ready `cioc` under `cca3`, README.MD and dist/files updated, I think everything is ok :smile:

**Comment by mledoze** [comment]
@cumanacr I just merged your pull request, thank you for your work!

**Comment by cumanacr** [comment]
@mledoze, my pleasure, have a nice day!

**Pull request merged**
