### PR TITLE
UN member states boolean flag

### PR DESCRIPTION
**Pull request by rkorzeniec**
Added `unMember` boolean flag. 
Currently there are 193 (according to [wikipedia](https://en.wikipedia.org/wiki/Member_states_of_the_United_Nations#Current_members) + [un offcial website](https://www.un.org/en/member-states/index.html), this leaves the other 57 states having the flag set to `false`

### CODE REVIEW

**Comment by rkorzeniec** [comment]
@mledoze friendly ping 😉

**Comment by mledoze** [comment]
Hello @rkorzeniec, I'm sorry for the delay, you know life, the quarantine and everything else...

I'll look into your pull request this week. Thank you for your work!

Meanwhile could you please add en entry in the changelog?

**Comment by mledoze** [comment]
The PR looks good. I just need the entry in the changelog before merging it.

**Comment by rkorzeniec** [comment]
@mledoze I totally understand, I was just worried that you abandoned it a bit, sine the other PRs haven't got much attention either in some time. 
I will go right ahead with the changelog. Would you like me to add it to `unreleased` section or create `4.1.0` section?

**Comment by rkorzeniec** [comment]
I added it to unreleased section for the time being. Much appreciated.

**Comment by mledoze** [comment]
It's merged, thank you for your work.

**Comment by rkorzeniec** [comment]
you're welcome 😉

**Pull request merged**
