### PR TITLE
Added Tamil to the list of Indian languages

### PR DESCRIPTION
**Pull request by Purus**
Added Tamil to the list of Indian languages

### CODE REVIEW

**Comment by herrniemand** [comment]
Sweet!*)

**Comment by hebrew878** [comment]
நானும் தமிழன்

**Comment by Purus** [comment]
Great to know fellow Tamilians :+1: 

Wish I could add all Indian languages to list. But I don't know translations of other languages.

**Comment by mledoze** [comment]
@Purus thank you! :+1:

**Pull request merged**
