### PR TITLE
Scandinavian common country names, Node stringify module

### PR DESCRIPTION
**Pull request by erwinw**
Scandinavian (Danish, Norwegian Bokmål and Swedish) common country names sourced from Wikipedia's ISO 3166-1 alpha-2 tables (where necessary supplemented by manual lookups).

Also, a Node module to stringify Countries json maintaining indentation and other details.

### CODE REVIEW

**Comment by herrniemand** [comment]
@mledoze Are you OK with taking care of this pull?

**Comment by mledoze** [comment]
Yes I'm OK. I need a bit more time to review everything.

@erwinw thank you for this pull!

**Comment by herrniemand** [comment]
@mledoze sweet.
@erwinw Yes. Sorry forgot. Thanks for pull. I will be looking at it through this week.

**Comment by herrniemand** [comment]
@erwinw I can see you are working on officials. Should I just leave PR with you until you finish with official names?

**Comment by erwinw** [comment]
@herrniemand I'm afraid not - haven't spotted an easy source for these.
Both: you're welcome!

**Comment by herrniemand** [comment]
@erwinw have you tried polyfilling with Google translate and then manually checking them?

**Comment by herrniemand** [comment]
@erwinw https://github.com/herrniemand/countries-dev/blob/master/scripts/Translate.py

**Comment by mledoze** [comment]
Hello @erwinw
have you managed to get official country names?

**Comment by dinbror** [comment]
Hi all.

Friendly ping :) Any progress on this or do you need help?

**Pull request closed without merging**
