### PR TITLE
Apply valid formatting to countries.json

### PR DESCRIPTION
**Pull request by fayder**
Currently the file countries.json does not follow any valid convention. **This makes it difficult to contribute to the project with automated scripts**. In order not to break the current formatting, contributors must do changes manually. 

This formatting makes it possible to contribute to json file with automated tools, that follow JSON conventions.

### CODE REVIEW

**Comment by mledoze** [comment]
Hello @fayder, thank you for this pull request. Which valid convention did you use for this proposal?

**Comment by fayder** [comment]
Hey! My bad about the currencies. I will do it in a separate PR of course. So, the formatting convention I'm proposing it's RFC 4627. Basically it changes arrays from their current form:
`"tld": [".aw"]`
to this form:
```
"tld": [
	".aw"
]
```
There are online formatters that also use this convention:
https://jsonformatter.curiousconcept.com
https://codebeautify.org/jsonviewer

It makes it much easier for me to contribute to the project, since I use automated scripts to make modifications, and these scripts also use this convention.

If this change is a burden on other contributors, I understand if you reject the PR

**Comment by fayder** [comment]
OK. I just noticed that the unicode escaped characters are also changed.... This is not intended 😞 Let me look into this a bit more

**Comment by fayder** [comment]
@mledoze I think now it is in the format I intended :)

**Comment by mledoze** [comment]
Thank you @fayder for the update, I'll review this today.

**Pull request closed without merging**
