### PR TITLE
Add build options to countries.php

### PR DESCRIPTION
**Pull request by petert82**
Hi,

I've taken the liberty of making a few changes to how the `countries.php` converter script works. I split the single script up into individual files in `src/` and added the symfony Console component as a dependency, to make it nice and easy to extend the conversion options in future.

Default build output should be identical to before, though the build command invocation has changed slightly; it is now `php countries.php convert` (documented in the CONTRIBUTING file ;) ).

As a result of the changes, it's now possible to specify at 'build' time that you would like to exclude certain data fields from the converted output (this is actually just exposing functionality that was already available in the `AbstractConverter`). This option is documented in the README, but boils down to simply providing one or more `--exclude-field`s when building. For example, to exclude `cca2` and `cca3`:

```sh
php countries.php convert --exclude-field=cca2 --exclude-field=cca3
```

Hope this not *too* big of a change! I wasn't sure what namespace to extract the classes from the build script into, so for now they all in `MLD\CountryData`, but they could easily be moved, if needed.

### CODE REVIEW

**Comment by herrniemand** [comment]
@petert82 what do you think about move src to .src, so it will be hidden in *nix systems?

**Comment by petert82** [comment]
@herrniemand I don't think there's any technical reason to prevent that. It's where it is now purely because - in the PHP projects I've seen - `src` tends to be the idiomatic home for stuff like this. Though given this isn't purely a PHP project, maybe there is a case for having the PHP source live somewhere else.

**Comment by mledoze** [comment]
@petert82 thank you for your contribution, it's a great addition! I'm testing it now locally. 

@herrniemand I concur with @petert82, there is no need to hide the `src` directory, it has its place with the new convert script proposed here.

**Comment by herrniemand** [comment]
@mledoze @petert82 agree with you guys*)

**Comment by mledoze** [comment]
> I wasn't sure what namespace to extract the classes from the build script into

@petert82 we could use `Countries` for the namespace.

**Comment by petert82** [comment]
@mledoze You're welcome!

The only thing that would put me off using `Countries` as the top-level namespace would be the possiblity of a namespace collision. Maybe `CountriesProject`?

**Comment by mledoze** [comment]
@petert82 I see, we'll keep it that way for now.

**Pull request merged**
