### PR TITLE
Emoji flags for countries

### PR DESCRIPTION
**Pull request by 8alery**
Flag for countries as emoji. Your already have flags in .svg files, but for some cases small symbol is all you need.

### CODE REVIEW

**Comment by herrjemand** [comment]
@8alery this is cool idea! Looking forward for the changes!

**Comment by JoseCage** [comment]
Very cool.. @8alery

**Comment by zoontek** [comment]
Can anyone generate the output and merge this?

**Comment by mledoze** [comment]
Hello, I'm sorry for the huge delay.

For this pull request to be accepted, the flags need to be JSON encoded, for example the Austrian flag (🇦🇹) becomes `\ud83c\udde6\ud83c\uddf9`.

@8alery do you think you can do that?

Thank you very much

**Comment by 8alery** [comment]
Hello!
@mledoze I replaced symbols in flag with JSON-safe version.

**Comment by blumk** [comment]
@8alery I've solved the merge conflicts and created a new PR, see #265

**Comment by mledoze** [comment]
I close this PR this it has been merged in #265. Thank you @8alery and @blumk for the good work!

**Comment by sabahang** [comment]
hi, can anyone point me to understand how to convert `\ud83c\udde6\ud83c\uddf9` to an actual flag on the web?

**Pull request closed without merging**
