### PR TITLE
Updated flags. Fixed Western Sahara.

### PR DESCRIPTION
**Pull request by herrniemand**
According to 
https://ar.wikipedia.org/wiki/%D8%A7%D9%84%D8%AC%D9%85%D9%87%D9%88%D8%B1%D9%8A%D8%A9_%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9_%D8%A7%D9%84%D8%B5%D8%AD%D8%B1%D8%A7%D9%88%D9%8A%D8%A9_%D8%A7%D9%84%D8%AF%D9%8A%D9%85%D9%82%D8%B1%D8%A7%D8%B7%D9%8A%D8%A9

And

https://en.wikipedia.org/wiki/Sahrawi_Arab_Democratic_Republic

I have fixed the official name(both native and english) and updated language code, which is Sawharin of Arab language (meh).

### CODE REVIEW

**Comment by herrniemand** [comment]
Its a hundreds pull request! :beers: for everyone!

**Comment by herrniemand** [comment]
Updated flags. All from Wikipedia, so now should be right. :shipit:

**Comment by herrniemand** [comment]
@mledoze I can not build ```dist```. 
```php
require_once "vendor/autoload.php";
```
What is it?

**Comment by mledoze** [comment]
> What is it?

Please see #92.

**Comment by herrniemand** [comment]
@mledoze I see. I guess I missed a bit of changes XD

**Comment by herrniemand** [comment]
I think we need to add part with composer to the ```CONTRIBUTING.md```

**Comment by mledoze** [comment]
We are good to go, merging now.

**Comment by mledoze** [comment]
@herrniemand good job! :+1:

**Comment by herrniemand** [comment]
@mledoze Thanks. 
Off to bed. 
Passe une bonne journée.

**Pull request merged**
