### PR TITLE
Make Kuwait border Iraq

### PR DESCRIPTION
**Pull request by JayChetty**

### CODE REVIEW

**Comment by herrniemand** [comment]
Thanks @JayChetty for the spotting problem. While you doing that, could you you remove IRN from KUWAIT borders. Because it borders only Iraq and Saudi. Here is proof:

| , it shares borders with Iraq and Saudi Arabia. As of 2014, Kuwait has a 
https://en.wikipedia.org/wiki/Kuwait
https://www.google.co.nz/maps/place/Kuwait/@30.0680369,48.5656625,9z/data=!4m2!3m1!1s0x3fc5363fbeea51a1:0x74726bcd92d8edd2

**Comment by JayChetty** [comment]
Yeah just noticed that!  Have made that change. @herrniemand

**Comment by herrniemand** [comment]
@JayChetty Ta*)

**Comment by mledoze** [comment]
@JayChetty @herrniemand thank you!

**Pull request merged**
