### PR TITLE
Allow both 2.7 and 3.0 for Symfony

### PR DESCRIPTION
**Pull request by DraperStudio**

### CODE REVIEW

**Comment by mledoze** [comment]
@DraperStudio thank you!

**Comment by DraperStudio** [comment]
Could you tag 1.7.5 so that projects which already have Symfony 3.0 installed can pull in this package?

**Comment by mledoze** [comment]
@DraperStudio done: https://github.com/mledoze/countries/releases/tag/v1.7.5

**Comment by DraperStudio** [comment]
Thanks, works!

**Pull request merged**
