### PR TITLE
Added landlocked information as proposed by @romsson. #6

### PR DESCRIPTION
**Pull request by herrniemand**
No description provided.

### CODE REVIEW

**Comment by herrniemand** [comment]
@mledoze *)

**Comment by mledoze** [comment]
@herrniemand I spotted an existing bug regarding `Saint Martin` and `Saint Pierre and Miquelon`. 

See here
https://github.com/mledoze/countries/blob/master/countries.json#L7713
and here
https://github.com/mledoze/countries/blob/master/countries.json#L7753

So, for `Saint Martin`, we should have:
```json
"name": {
	"common": "Saint Martin",
	"official": "Saint Martin",
	"native": {
		"common": "Saint-Martin",
		"official": "Saint-Martin"
	}
}
```
and for `Saint Pierre and Miquelon`
```json
"name": {
	"common": "Saint Pierre and Miquelon",
	"official": "Saint Pierre and Miquelon",
	"native": {
		"common": "Saint-Pierre-et-Miquelon",
		"official": "Collectivité territoriale de Saint-Pierre-et-Miquelon"
	}
}
```

Could you make these changes before I merge this PR?

Again, thank you for your help!

**Comment by herrniemand** [comment]
@mledoze gimme a sec*)

**Comment by herrniemand** [comment]
@mledoze I am confused.

**Comment by herrniemand** [comment]
@mledoze so there should be two different objects?

**Comment by herrniemand** [comment]
@mledoze XD I got confused cause they next to each other
XD

**Comment by herrniemand** [comment]
@mledoze Done*)

**Comment by mledoze** [comment]
@herrniemand indeed they are next to each other in this file but in reality, they are really far apart :)

**Comment by herrniemand** [comment]
@mledoze *)
Our projects moto:  ```countries.json Bringing countries closer together.``` XD

**Comment by mledoze** [comment]
@herrniemand superb! Merging now.

**Pull request merged**
